BBMRI-ERIC/negotiator-frontend

- src/auth.js
Fixes wrong token expiration (see https://github.com/BBMRI-ERIC/negotiator-v3/issues/34)
> fix: fixes token expiration

- package.json
- src/components/NegotiationForm.vue
- src/store/actions.js
- src/store/state.js
- tests/views/HomePage.spec.js
- yarn.lock
This PR does the following:
- it gets the resource for which access criteria are needed dynamically starting from the request id (N.B: currently the resourceId considered is the one of the first biobank in the original request)
- it adds a notification if something wrong happens when getting access criteria
- it creates the unit test skeleton with some tests for the homepage
> feat: now it gets access criteria of the first bioank in the request

- src/components/NavigationBar.vue
- src/components/OidcCallback.vue
- src/views/HomePage.vue
fixes redirect to home page when it the user is logged in
> fix: fixes redirect to home page when it the user is logged in

- src/components/NegotiationList.vue
- src/views/NegotiationPage.vue
> fix: fixes roles string

- src/components/NegotiationForm.vue
Added info icon, with description dropdown to request submission form.
> 62-63 add description info icon

- src/components/NegotiationList.vue
- fix counter to display total elements in database and not on page
> fix counter to display right information

- src/views/NegotiationPage.vue
- Show email on Negotiation page below Author information
> add email to negotiation page

- src/App.vue
fix: vue-tour display on request page
- vue-tou is now displayed only on predefined pages
- refactored App.vue component to Composition API
> fix: vue-tour display on request page

- README.md
- docs/FOOTER_CONFIGURATION.md
- src/components/Footer.vue
- src/config/theme.js
- start.sh
Adds configuration options for information displayed in footer component.
> Additional configuration for links and information in footer.

- src/views/HomePage.vue
fix: hide login page if user is Authenticated
> fix: hide login page if user is alredy loged-in

- src/views/NegotiationPage.vue
reload page only after all resource is updated
> fix: reload page after resource is updated

- src/components/VueTour.vue
when you click on skip button vue tour wont show enymore
> fix: dont show vue tour on skip button

- src/components/CopyTextButton.vue
- src/views/NegotiationPage.vue
feat: added window for search parameters and collection id with copy button
> feat: add search parameters and collection id

- src/components/NegotiationPosts.vue
Bugfix for uploading attachments and messages in one go.
> Bugfix for uploading attachments and messages in one go

- start.sh
Reverts BBMRI-ERIC/negotiator-frontend#253
> Revert "Fix start script"

- src/components/Footer.vue
- src/components/NegotiationList.vue
- src/components/Notifications.vue
- src/views/HomePage.vue
- src/views/NegotiationPage.vue
fix paddings, layout
add action field to table
> Fix: page layout paddings table, action

- src/components/NegotiationPosts.vue
- src/store/negotiationPage.js
Cleans up the code and the UI for comments. Please test with this backend [version](https://github.com/BBMRI-ERIC/negotiator/pull/449)
> refactor: negotiation posts component

- .github/workflows/CI.yml
- src/components/NegotiationForm.vue
- src/views/NegotiationPage.vue
changes the frontend to be compatible with https://github.com/BBMRI-ERIC/negotiator/pull/459
> refactor: post negotiation data with just one request

- src/components/Footer.vue
fix: show build version on prod, becaouse pinia is not persistant on refresh
> fix: footer actuator Info backend version on prod, acc

- src/components/Footer.vue
- src/views/HomePage.vue
Changed display text to AGPLv3.
> Change text from LGPLv3 to AGPLv3
